### ISSUE TITLE
Azure Active Directory Redirect URL always routing htttp 

### ISSUE THREAD

**Issue by nihatakin** [EdiWang/Elf#55]
I uploaded the azure environment with powershell and I configured all environment for the Azure AD but redirect_url always set http.

**Comment by EdiWang** [comment]
What type of deployment are you using? Docker or Code publish?

**Comment by nihatakin** [comment]
Docker

**Comment by EdiWang** [comment]
Closed as no longer valid issue. AAD Login is now using SPA mode with JWT.
